// ⚠️ Auto-generated by encrypt-contact.js. Do NOT edit by hand.
export const encryptedContactData = "QEzWICzvl+v/n7VLOTB5f1nw2bsxxscuS2C4rhFGq2kyfmO8umMm135tlNxseALzbIeKKbtJeUTk0CcjNDbXtlXdYog3jMwizFw3ahlaSQBPAxSiKksxSk+UZkk/l+jxV4RzU8pDDCg=";
