// ⚠️ Auto-generated by encrypt-contact.js. Do NOT edit by hand.
export const encryptedContactData = "C6uoaKfFypgoJCFZqfiAiJ1vauT49sV4ydS2RHOXsbmkVrZ1YP1YRpzoIGdQkS0YRtI6izQyiIlXsGoP0qjSM7CpdoVLpuJiKmjJjCH3jtBanYM2YBY/wv0zjg6UGlRbe+UD7ewY3Vo=";
