// ⚠️ Auto-generated by encrypt-contact.js. Do NOT edit by hand.
export const encryptedContactData = "xoZGmBp3o4D/tD9xv28MQENA606FMWpJZZxNb0s+i0Wx2q+9Xx27Y1pH6Ya8BvStQqtbAvw41qQEK3e41Cjbn2z2V6yo0hQOrgiMJh8l1uhdtiacpFupQ7ea1j7uq7EDPYsF4w==";
