// scripts/encrypt-contact.js
//
// Run with:  node scripts/encrypt-contact.js
//
// It will ask for Email, Phone, and Password (masked).
// Then it prints a single Base64 string: [ salt | iv | authTag | ciphertext ].
//
// You can paste that Base64 into your static Next.js page.

const crypto = require("crypto");
const readline = require("readline");

// Create a readline interface for the first two questions
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

function ask(questionText) {
    return new Promise((resolve) => {
        rl.question(questionText, (answer) => {
            resolve(answer.trim());
        });
    });
}

// Prompt for a password but mask input with asterisks
function askPassword(promptText) {
    return new Promise((resolve) => {
        const stdin = process.stdin;
        const stdout = process.stdout;
        let password = "";

        stdout.write(promptText);
        stdin.resume();
        stdin.setRawMode(true);

        const onData = (char) => {
            char = char.toString();

            switch (char) {
                case "\r":
                case "\n":
                case "\u0004":
                    // Enter or Ctrl-D: finish
                    stdin.setRawMode(false);
                    stdout.write("\n");
                    stdin.removeListener("data", onData);
                    resolve(password);
                    break;
                case "\u0003":
                    // Ctrl-C: exit
                    process.exit();
                    break;
                default:
                    // mask any other character
                    stdout.write("*");
                    password += char;
                    break;
            }
        };

        stdin.on("data", onData);
    });
}

;(async () => {
    try {
        // prompt for info and password
        const email = await ask("Enter email: ");
        const phone = await ask("Enter phone: ");
        const password = await askPassword("Enter password: ");
        rl.close();

        // derive a 32-byte key from password using PBKDF2
        const salt = crypto.randomBytes(16); // 16-byte salt
        const key = crypto.pbkdf2Sync(password, salt, 500_000, 32, "sha256");

        // encrypt the JSON payload with AES-256-GCM
        const payload = JSON.stringify({ email, phone });
        const iv = crypto.randomBytes(12); // 12-byte IV for GCM

        const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
        const ciphertext = Buffer.concat([cipher.update(payload, "utf8"), cipher.final()]);
        const authTag = cipher.getAuthTag(); // 16-byte tag

        // combine: [ salt (16) | iv (12) | authTag (16) | ciphertext (...) ]
        const combined = Buffer.concat([salt, iv, authTag, ciphertext]);
        const base64 = combined.toString("base64");

        // write out to file
        const fs = require("fs");
        const path = require("path");
        const outPath = path.join(__dirname, "../app/contact/encrypted.ts");
        const fileContents = `
        // ⚠️ Auto-generated by encrypt-contact.js. Do NOT edit by hand.
        export const encryptedContactData = "${base64}";
        `.replace(/^[ \t]+/gm, '').trimStart();
        fs.writeFileSync(outPath, fileContents, "utf8");
        + console.log(`\n→ Wrote encrypted blob to ${outPath}\n`);
    } catch (err) {
        console.error("Error:", err);
        process.exit(1);
    }
})();
